# **Module `pepper.np_utils`**

✔ Revue des **typehints** et des **docstrings**.

# **`subindex`**`(a, sorted)`

In [1]:
import numpy as np
from pepper.np_utils import subindex

a = np.array([0, 0, 1, 1, 1, 3, 5, 5, 11, 11, 11, 11])
subindex(a)

array([0, 1, 0, 1, 2, 0, 0, 1, 0, 1, 2, 3])

In [2]:
import numpy as np
from pepper.np_utils import subindex

a = np.array([1, 11, 5, 11, 1, 11, 5, 0, 3, 11, 0, 1])
subindex(a)

array([0, 0, 0, 1, 1, 2, 1, 0, 0, 3, 1, 2])

# **`subindex_nd`**`(a, sorted)`

In [1]:
import numpy as np
from pepper.np_utils import subindex_nd

a = np.array([[0, 1], [0, 1], [1, 2], [1, 2], [1, 2]])
subindex_nd(a)

array([0, 1, 0, 1, 2])

# **`ndarray_to_list`**`(arr)`

In [3]:
import numpy as np
from pepper.np_utils import ndarray_to_list

s = [[1, 2], [3, 4]]
a = np.array(s)
display(a)
display(ndarray_to_list(a))

array([[1, 2],
       [3, 4]])

[[1, 2], [3, 4]]

# **`reconstruct_ndarray`**`(arr)`

Le besoin de cette fonction s'est manifesté au moment de la sauvegarde de ndarrays avec Parquet.

Parquet ne support à l'heure actuelle que les ndarray 1D.

En cas de sauvegarde d'objets multidimensionnels (`ndarray`, `list` ou `tuple`), il les convertit en structure imbriquée de `ndarray` 1D.

Au moment du chargement de la sauvegarde, il faut donc recomposer le tableau multidimensionnel.

In [1]:
import numpy as np
from pepper.np_utils import reconstruct_ndarray

x = [
    np.array([(1, 2, 3), (4, 5, 6)]),
    np.array([(7, 8, 9), (10, 11, 12)])
]
display(x)
display(reconstruct_ndarray(x))

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Cas limite :

In [2]:
x = [[]]
display(x)
display(reconstruct_ndarray(x))

[[]]

array([], shape=(1, 0), dtype=float64)